version: '3'
services:
  db:
    image: mysql:latest
    volumes:
      - ./mysql-data/db:/var/lib/mysql/
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: demo
      MYSQL_USER: user
      MYSQL_PASSWORD: pass